### ISSUE TITLE
Document server

### ISSUE THREAD

**Issue by kpu** [marian-nmt/marian-nmt.github.io#13]
https://marian-nmt.github.io/docs/ makes no reference to marian-server or how to use it.  I see there is https://github.com/marian-nmt/marian-dev/blob/master/scripts/server/client_example.py so this may just be a matter of pointing people to it.

**Comment by snukky** [comment]
Some documentation for `marian-server` is now here: https://marian-nmt.github.io/docs/#marian-web-server
