### ISSUE TITLE
Is there a latex -> mathML plugin?

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-nmt.github.io#14]
Just asking, would be cool to have and be able to include proper math on the pages.

**Comment by snukky** [comment]
Kramdown supports MathJax. I enabled it on all pages with `latex: true` in front matter (see docs/index.md and faq.md). 
Documentation: https://kramdown.gettalong.org/syntax.html#math-blocks

**Comment by emjotde** [comment]
Great, thanks,
