### ISSUE TITLE
Minor typo on MTM19 tutorial =)

### ISSUE THREAD

**Issue by alvations** [marian-nmt/marian-nmt.github.io#23]
Minor typo on https://marian-nmt.github.io/examples/mtm2019 

From:

> The tutorial requires Marian in version v1.7.12+, which is currently only available in the marian-dev repository. However, most parts are also **pplicable** for older versions of Marian.

to:

> The tutorial requires Marian in version v1.7.12+, which is currently only available in the marian-dev repository. However, most parts are also **applicable** for older versions of Marian.

**Comment by snukky** [comment]
Fixed. Thanks!
