### ISSUE TITLE
Model for MTM19 Part 2

### ISSUE THREAD

**Issue by alvations** [marian-nmt/marian-nmt.github.io#24]
Is there a trained model for the Part 2. of the MTM19 tutorial? 

Just for sanity check against students' trained model.

**Comment by snukky** [comment]
Sorry for the late response, somehow I wasn't watching this repo. We have some of our student models from the WNGT 2018 shared task available from http://data.statmt.org/romang/marian-regression-tests/models/wnmt18/ and we will upload student models from this year soon, when I add then to the regression tests. We are also planning a tutorial on the teacher-student method, but this will come in a medium-term future.

**Comment by alvations** [comment]
@snukky Quick catch that's related, on https://marian-nmt.github.io/docs/#guided-alignment , sed command for `fast_align` is incomplete. Should have been:

```
paste corpus.en corpus.de | sed 's/\t/ ||| /g' > corpus.en-de
```

**Comment by snukky** [comment]
Fixed. Thanks!
