### ISSUE TITLE
Add zoom to clickable images for blog benchmarks etc.

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-nmt.github.io#27]
Currently when clicking an image it has to be turned into a link in order to open a larger version. Would be nice to be able to have a zoom (or closable larger version on the page). Also captions over or under the image.

**Comment by snukky** [comment]
I added [Jekyll Lightbox](https://jekyllcodex.org/without-plugin/lightbox), which adds an imagebox to each image, and extended it a bit to display captions. A caption is taken from a "title" attribute of the hyperlink if it exists, or "alt" from the image subelement, or raw text from the hyperlink). Works only for posts. Added only to the jekyll branch.

**Comment by emjotde** [comment]
Wow, that is really great!
