### ISSUE TITLE
Ubuntu 14.04 Prerequisites Incorrect

### ISSUE THREAD

**Issue by kdavis-mozilla** [marian-nmt/marian-nmt.github.io#28]
The [prerequisites](https://github.com/marian-nmt/marian-nmt.github.io/blob/79ff38f817b14b9404cf1c6d07d793b80aa1c455/docs/index.html#L302) for Ubuntu 14.04 are invalid.

Upon attempting to compile after installing the suggested prerequisites, a warning is raised that g++ 5 or later is required.

g++  5 or later is not a part of the base Ubuntu 14.04 system and is not on the list of required prerequisites.

**Comment by snukky** [comment]
Thanks for noticing this! I am in the middle of updating the website for the current release.
CUDA <9 and GCC <5 are no longer supported with the release 1.9.

This GCC/CUDA compatibility table might be useful too: https://github.com/marian-nmt/marian-dev/issues/526#issue-513652890

**Comment by snukky** [comment]
I added information about gcc 5+ and cuda 9+ requirements on Ubuntu 14.04.
