### ISSUE TITLE
marian-conv documentation url

### ISSUE THREAD

**Issue by ahtaie** [marian-nmt/marian-nmt.github.io#29]
The url for marian-conv's documentation redirects to marian-vocab. Changing it to /marian-conv in the url correctly gets me there though.

And speaking of documentation, any hope of getting some user guide for factored vocab (for both src and tgt)? We want to use it, and tried to reverse engineer it (with .fsv) but it does not seem straightforward to me. There is an issue about it here: [#276](https://github.com/marian-nmt/marian/issues/276). Thanks!

**Comment by snukky** [comment]
Good catch, many thanks! Fixed.

Regarding factored models, I believe there will be a user guide as soon as everything what is needed for factored training is included in the Marian code base. AFAIK, some pieces are still missing.
