### ISSUE TITLE
Add info about automatic GitHub builds in README

### ISSUE THREAD

**Issue by snukky** [marian-nmt/marian-nmt.github.io#34]
Adding as a reminder that we should mention in README that master is now automatically updated via GitHub actions, that the workflow can be started manually from GitHub UI, and that using this is now preferred over `commit-and-deploy.sh`.

Extracted from https://github.com/marian-nmt/marian-nmt.github.io/pull/32#pullrequestreview-616213048

**Comment by graemenail** [comment]
Closed by #38
