### ISSUE TITLE
Website still says there is no support for Windows

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-nmt.github.io#35]
While there is :)
https://github.com/marian-nmt/marian-dev/tree/master/vs

**Comment by emjotde** [comment]
I see that in the FAQ and not pointers to Windows under installation instructions.

**Comment by snukky** [comment]
Fixed. The documentation and FAQs need a general refreshment and we will do that as we are slowly working on moving the documentation to the main repo.
