### ISSUE TITLE
Widen the space for command line options to avoid wrapping

### ISSUE THREAD

**Issue by kpu** [marian-nmt/marian-nmt.github.io#37]
The command line documentation is really terribly formatted for me (Firefox on Linux, no zoom): it wraps a few characters to the next line.  
![wrap_fail](https://user-images.githubusercontent.com/247512/118654043-0dfa5900-b7e0-11eb-9059-4b95dc431b06.png)

**Comment by snukky** [comment]
It's been fixed with recent changes to the website. It still happens, but only if zoomed in.
